Smooth : Smooth.cpp
	g++ -g -Wall -o Smooth Smooth.cpp -lpthread

run orig:
	./Smooth 1 output_origin.bmp
2:
	./Smooth 2 output_2.bmp
4:
	./Smooth 4 output_4.bmp
8:
	./Smooth 8 output_8.bmp
16:
	./Smooth 16 output_16.bmp

clean:
	rm Smooth
